"""Service layer: AI and image processing business logic."""

from app.services.ai_engine import generate_product_image, generate_product_image_for_tariff
from app.services.admin_service import (
    AdminErrorLogView,
    AdminNotFoundError,
    AdminService,
    AdminServiceError,
    AdminStatistics,
    AdminUserView,
    AdminValidationError,
)
from app.services.billing_service import (
    BillingError,
    BillingNotFoundError,
    BillingResult,
    BillingService,
    BillingValidationError,
    compute_subscription_end,
    describe_tariff,
)
from app.services.infographic_service import (
    InfographicPackage,
    InfographicService,
    InfographicServiceError,
    InfographicValidationError,
    LLMConfig,
    LLMIntegrationError,
    TextPlacement,
    generate_infographic_package,
)
from app.services.s3_storage import (
    S3StorageConfigurationError,
    S3StorageError,
    S3UploadResult,
    SelectelS3Storage,
    get_s3_storage,
)
from app.services.series_generator import (
    DEFAULT_SLIDE_OVERLAY_TEXTS,
    SERIES_SLIDE_CONCURRENCY,
    SeriesArchiveResult,
    SeriesGenerationError,
    SeriesResult,
    SeriesTask,
    apply_text_overlays_to_series,
    build_series_tasks,
    build_series_zip_bytes,
    build_series_zip_to_path,
    generate_slide_series,
    generate_slide_series_archive,
    package_series_archive_to_s3,
    save_series_images_locally,
)
from app.services.tariffs import (
    TARIFF_CATALOG,
    TariffPlan,
    get_tariff_plan,
    list_tariff_plans,
)
from app.services.yookassa_service import (
    YooKassaConfigurationError,
    YooKassaError,
    YooKassaPaymentCreated,
    YooKassaService,
    YooKassaUpstreamError,
    get_yookassa_service,
)

__all__ = [
    "generate_product_image",
    "generate_product_image_for_tariff",
    "AdminService",
    "AdminServiceError",
    "AdminNotFoundError",
    "AdminValidationError",
    "AdminStatistics",
    "AdminUserView",
    "AdminErrorLogView",
    "BillingService",
    "BillingError",
    "BillingNotFoundError",
    "BillingValidationError",
    "BillingResult",
    "compute_subscription_end",
    "describe_tariff",
    "LLMConfig",
    "TextPlacement",
    "InfographicPackage",
    "InfographicService",
    "InfographicServiceError",
    "InfographicValidationError",
    "LLMIntegrationError",
    "generate_infographic_package",
    "SelectelS3Storage",
    "S3StorageError",
    "S3StorageConfigurationError",
    "S3UploadResult",
    "get_s3_storage",
    "SeriesTask",
    "SeriesResult",
    "SeriesArchiveResult",
    "SeriesGenerationError",
    "SERIES_SLIDE_CONCURRENCY",
    "DEFAULT_SLIDE_OVERLAY_TEXTS",
    "build_series_tasks",
    "build_series_zip_bytes",
    "build_series_zip_to_path",
    "generate_slide_series",
    "generate_slide_series_archive",
    "package_series_archive_to_s3",
    "save_series_images_locally",
    "apply_text_overlays_to_series",
    "TARIFF_CATALOG",
    "TariffPlan",
    "get_tariff_plan",
    "list_tariff_plans",
    "YooKassaService",
    "YooKassaError",
    "YooKassaConfigurationError",
    "YooKassaUpstreamError",
    "YooKassaPaymentCreated",
    "get_yookassa_service",
]
