"""API / persistence DTO schemas (Pydantic v2)."""

from app.schemas.generate_pipeline import (
    GeneratePipelineRequest,
    GeneratePipelineResponse,
    PipelineBadge,
    PipelineLayerUrls,
)
from app.schemas.generations import (
    GenerationCreateResponse,
    GenerationErrorResponse,
    GenerationForm,
    GenerationHistoryItemResponse,
    GenerationSlideResponse,
    GenerationStatusResponse,
    MarketplaceTextResponse,
    ModelModeRequest,
)
from app.schemas.templates import (
    BadgeLayerDTO,
    BadgeType,
    BaseLayerDTO,
    CanvasLayerDTO,
    CanvasStateDTO,
    DesignRenderRequest,
    DesignRenderResponse,
    ImageLayerDTO,
    LayerAlignment,
    LayerType,
    SavedDesignDTO,
    SavedDesignListResponse,
    SaveDesignRequest,
    ShapeLayerDTO,
    ShapeType,
    TemplateDetailDTO,
    TemplateListResponse,
    TemplateSummaryDTO,
    TextLayerDTO,
)

__all__ = [
    "BadgeLayerDTO",
    "BadgeType",
    "BaseLayerDTO",
    "CanvasLayerDTO",
    "CanvasStateDTO",
    "DesignRenderRequest",
    "DesignRenderResponse",
    "GeneratePipelineRequest",
    "GeneratePipelineResponse",
    "GenerationCreateResponse",
    "GenerationErrorResponse",
    "GenerationForm",
    "GenerationHistoryItemResponse",
    "GenerationSlideResponse",
    "GenerationStatusResponse",
    "ImageLayerDTO",
    "LayerAlignment",
    "LayerType",
    "MarketplaceTextResponse",
    "ModelModeRequest",
    "PipelineBadge",
    "PipelineLayerUrls",
    "SaveDesignRequest",
    "SavedDesignDTO",
    "SavedDesignListResponse",
    "ShapeLayerDTO",
    "ShapeType",
    "TemplateDetailDTO",
    "TemplateListResponse",
    "TemplateSummaryDTO",
    "TextLayerDTO",
]
